# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# Gitleaks configuration for secret scanning

[extend]
# Use default gitleaks rules
useDefault = true

# Add custom rules or allowlists here if needed
