# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: OpenSSF Scorecard Analysis
on:
  schedule:
    # Saturdays at 01:50 UTC
    - cron: "50 1 * * 6"
    # Wednesdays at 01:50 UTC
    - cron: "50 1 * * 3"
  workflow_dispatch:

permissions:
  contents: read # Best Security practice. Jobs only get read as base, and then permissions are added as needed

jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@10c4365f9e61bc72bdd618e7b11f8d427eb2d5fa # v2.1.1
    with:
      publish-results: true
